# Generated by Django 5.0.2 on 2024-07-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(),
        ),
    ]
