name: djangobnb_backend

services:
  web:
    build: ./djangobnb_backend
    command:  >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangobnb_backend/:/usr/src/djangobnb_backend/
    ports:
      - 8000:8000
    networks:
      - postgres
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: gyari12@gmail.com
      PGADMIN_DEFAULT_PASSWORD: adam1234
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
  pgadmin: